### ISSUE TITLE
Correct Readme.md

### ISSUE THREAD

**Issue by BiDuang** [realmelangez/minecraft_font#1]
Great work! This project is really awesome!
`Minecraft is a video game created and maintained by Mojang Studios of Microsoft.`
I think Minecraft was created by Markus Persson whose nickname is Notch. 
Not Microsoft.

Glad to receive your reply.

**Comment by BiDuang** [comment]
Also, you need to set up a license to avoid commercial use.

**Comment by realmelangez** [comment]
qwq
